# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: "/Oskihacks"

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://hubi0111.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Oski Hacks | April 2023"
  description: "WOW SUPER COOL BERKELEY IEEE HACKATHON FEATURING OSKI!!!!!"
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Oski Hacks"
  description: "WOW SUPER COOL BERKELEY IEEE HACKATHON FEATURING OSKI!!!!!"
  date:        "April 22-23 2023"
  location:    "Berkeley, CA, United States"

  hero:
    links:
      - text: "Apply"
        href: "https://airtable.com/shrN4Fn5j3RcIbpMf"
      - text: "Sponsor"
        href: "mailto:ieee@berkeley.edu"

  about:
    description: >
      Adi will give me stuff to put here.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          And here.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          And here.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          And here.

  # Frequently asked questions.
  faq:
    - question: "What questions are there?"
      answer: >
        idk ask Adi.


  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
